# Generated by Django 3.2.5 on 2021-12-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
