# Generated by Django 3.2.5 on 2021-12-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='imageurl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
