# Generated by Django 3.2.5 on 2021-12-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_link_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[], max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
