# Generated by Django 3.2.5 on 2021-12-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(choices=[('Công nghệ', 'Công nghệ'), ('Du lịch', 'Du lịch'), ('Giáo dục', 'Giáo dục'), ('Giải trí', 'Giải trí'), ('Kinh doanh', 'Kinh doanh'), ('Nhịp sống', 'Nhịp sống'), ('Phim ảnh', 'Phim ảnh'), ('Pháp luật', 'Pháp luật'), ('Sống trẻ', 'Sống trẻ'), ('Sức khỏe', 'Sức khỏe'), ('Thế giới', 'Thế giới'), ('Thể thao', 'Thể thao'), ('Thời sự', 'Thời sự'), ('Thời trang', 'Thời trang'), ('Xe', 'Xe'), ('Xuất bản', 'Xuất bản'), ('Ẩm thực', 'Ẩm thực'), ('Âm nhạc', 'Âm nhạc')], max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='label',
            field=models.CharField(choices=[('Công nghệ', 'Công nghệ'), ('Du lịch', 'Du lịch'), ('Giáo dục', 'Giáo dục'), ('Giải trí', 'Giải trí'), ('Kinh doanh', 'Kinh doanh'), ('Nhịp sống', 'Nhịp sống'), ('Phim ảnh', 'Phim ảnh'), ('Pháp luật', 'Pháp luật'), ('Sống trẻ', 'Sống trẻ'), ('Sức khỏe', 'Sức khỏe'), ('Thế giới', 'Thế giới'), ('Thể thao', 'Thể thao'), ('Thời sự', 'Thời sự'), ('Thời trang', 'Thời trang'), ('Xe', 'Xe'), ('Xuất bản', 'Xuất bản'), ('Ẩm thực', 'Ẩm thực'), ('Âm nhạc', 'Âm nhạc')], max_length=255),
        ),
    ]
